### PR TITLE
make debug builds separate because they should be

### PR DESCRIPTION
**Pull request by SmallPP420**
imagine this

hey dude which exe should i download
the normal one
dude which one
the none debug one
ohhhh

this is why debug builds should be separate (added dev tags to hopefully remove any confoosion)

### CODE REVIEW

**Comment by SmallPP420** [comment]
donkey fart
@usrDottik

**Comment by usrDottik** [comment]
:(

**Comment by SmallPP420** [comment]
soz

**Comment by SmallPP420** [comment]
:((

**Comment by usrDottik** [comment]
reverted as in 1/12/2022

**Comment by SmallPP420** [comment]
man

**Comment by usrDottik** [comment]
> man

man

**Comment by SmallPP420** [comment]
u making this sink in :((((((((

**Pull request merged**
